module.exports = {
  addField: require('./add-field'),
  asJson: require('./as-json'),
  clear: require('./clear'),
  disableValidation: require('./disable-validation'),
  enableValidation: require('./enable-validation'),
  getGroupedValidationMessages: require('./get-grouped-validation-messages'),
  getValidationMessages: require('./get-validation-messages'),
  get: require('./get'),
  getInitial: require('./get-initial'),
  hasBeenValidated: require('./has-been-validated'),
  isDirty: require('./is-dirty'),
  isValid: require('./is-valid'),
  markFieldAsClean: require('./mark-field-as-clean'),
  markFieldAsDirty: require('./mark-field-as-dirty'),
  removeField: require('./remove-field'),
  reset: require('./reset'),
  resetWithData: require('./reset-with-data'),
  set: require('./set'),
  validate: require('./validate')
};